import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

interface TranscriptEntry {
  speaker: 'AI' | 'User'
  text: string
  timestamp: string
}

interface AnalysisRequest {
  sessionId: string
  transcript: TranscriptEntry[]
  interviewType: string
  duration?: number
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  try {
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
    )

    const { sessionId, transcript, interviewType, duration }: AnalysisRequest = await req.json()

    if (!sessionId || !transcript || transcript.length === 0) {
      throw new Error('Session ID and transcript are required')
    }

    console.log(`🔍 Starting analysis for session: ${sessionId}`)

    // Format transcript for analysis
    const formattedTranscript = transcript
      .map(entry => `${entry.speaker}: ${entry.text}`)
      .join('\n')

    // Create analysis prompt
    const analysisPrompt = `
Analyze the following job interview transcript and provide a comprehensive evaluation:

INTERVIEW TYPE: ${interviewType}
DURATION: ${duration || 'Unknown'} minutes

TRANSCRIPT:
${formattedTranscript}

Please provide a detailed analysis in the following JSON format:
{
  "overall_score": [score from 1-100],
  "communication_score": [score from 1-100],
  "technical_score": [score from 1-100],
  "confidence_score": [score from 1-100],
  "problem_solving_score": [score from 1-100],
  "strengths": ["strength1", "strength2", "strength3"],
  "areas_for_improvement": ["area1", "area2", "area3"],
  "feedback": "Detailed constructive feedback paragraph",
  "transcript_summary": "Brief summary of the interview content"
}

Focus on:
- Communication clarity and structure
- Technical knowledge and problem-solving approach
- Confidence and presentation
- Areas for improvement with specific actionable advice
- Overall interview performance

Return ONLY the JSON object, no additional text.
`

    // Call OpenAI API
    console.log('📤 Sending request to OpenAI API...')
    const openaiResponse = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${Deno.env.get('OPENAI_API_KEY')}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'gpt-4o-mini',
        messages: [
          {
            role: 'system',
            content: 'You are an expert interview analyst. Provide detailed, constructive feedback on interview performance. Always respond with valid JSON only.'
          },
          {
            role: 'user',
            content: analysisPrompt
          }
        ],
        temperature: 0.3,
        response_format: { type: "json_object" }
      }),
    })

    if (!openaiResponse.ok) {
      const errorText = await openaiResponse.text()
      console.error('❌ OpenAI API error:', errorText)
      throw new Error(`OpenAI API error: ${openaiResponse.status} - ${errorText}`)
    }

    const openaiData = await openaiResponse.json()
    console.log('✅ Received response from OpenAI API')

    if (!openaiData.choices || openaiData.choices.length === 0) {
      throw new Error('No analysis generated by OpenAI')
    }

    // Parse the analysis response
    let analysisData
    try {
      const analysisText = openaiData.choices[0].message.content.trim()
      console.log('🔍 Parsing OpenAI response:', analysisText.substring(0, 200) + '...')
      
      analysisData = JSON.parse(analysisText)
    } catch (parseError) {
      console.error('❌ Failed to parse OpenAI response:', parseError)
      // Fallback analysis if parsing fails
      analysisData = {
        overall_score: 75,
        communication_score: 75,
        technical_score: 70,
        confidence_score: 80,
        problem_solving_score: 70,
        strengths: ['Good communication', 'Shows enthusiasm', 'Relevant experience'],
        areas_for_improvement: ['Provide more specific examples', 'Structure answers better', 'Show more technical depth'],
        feedback: 'The candidate showed good communication skills and enthusiasm. To improve, focus on providing more specific examples and structuring answers with clear frameworks like STAR method.',
        transcript_summary: 'Interview discussion covering background, experience, and technical capabilities.'
      }
    }

    // Get user from session
    const { data: { user } } = await supabaseClient.auth.getUser()
    if (!user) {
      throw new Error('User not authenticated')
    }

    // Save analysis to database
    const analysisRecord = {
      user_id: user.id,
      interview_type: interviewType,
      duration_minutes: duration || null,
      overall_score: analysisData.overall_score || null,
      communication_score: analysisData.communication_score || null,
      technical_score: analysisData.technical_score || null,
      confidence_score: analysisData.confidence_score || null,
      problem_solving_score: analysisData.problem_solving_score || null,
      strengths: analysisData.strengths || [],
      areas_for_improvement: analysisData.areas_for_improvement || [],
      feedback: analysisData.feedback || '',
      transcript_summary: analysisData.transcript_summary || '',
    }

    console.log('💾 Saving analysis to database...')
    const { data: savedAnalysis, error: saveError } = await supabaseClient
      .from('interview_analyses')
      .insert([analysisRecord])
      .select()
      .single()

    if (saveError) {
      console.error('❌ Error saving analysis:', saveError)
      throw saveError
    }

    console.log('✅ Analysis saved successfully:', savedAnalysis.id)

    return new Response(
      JSON.stringify({
        success: true,
        analysisId: savedAnalysis.id,
        analysis: analysisData,
        message: 'Interview analysis completed successfully'
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      },
    )

  } catch (error: any) {
    console.error('❌ Interview analysis error:', error)
    
    return new Response(
      JSON.stringify({
        success: false,
        error: error.message,
        message: 'Failed to analyze interview'
      }),
      {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      },
    )
  }
})