// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsqiupbfspkatnvvllzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzcWl1cGJmc3BrYXRudnZsbHpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMTc0MzYsImV4cCI6MjA2NTc5MzQzNn0.DgNFyuAwEi2LKgiluXs1w3GMfwpyOgyX61Dojcjzb0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});